### ISSUE TITLE
Retrieve authenticated principal information in a controller

### ISSUE THREAD

**Issue by okonon** [sansmoraxz/aws-cognito-customauth-springboot3#1]
Hi and thank you for your work. I have a quick question. How can i retrieve authenticated principal information in a controller ? thanks

**Comment by sansmoraxz** [comment]
Depends on what you define as principal. You may implement/ create a custom bean for `JwtAuthenticationConverter`.

Alternatively you can use the SPEL syntax. I have not created a bean cause I wanted to play it loose with various use cases (`id` tokens are techincally not oauth tokens).

For instance you are using [mapping IAM roles](https://docs.aws.amazon.com/cognito/latest/developerguide/role-based-access-control.html#using-tokens-to-assign-roles-to-users).

You may add the following into your controller:

```java
@AuthenticationPrincipal(expression = "claims['cognito:roles']") List<String> iamRoles
```

Or `"cognito:groups"` if you want to manage with [group based access](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-user-groups.html) and so on.

**Comment by okonon** [comment]
Thanks that helps
